# -*- coding: utf-8 -*-
"""Logic Building Task – 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsRjT9fJ11jIYW5jrRWOKnFw5zOV6lYH

1. User Login Check
"""

# credentials stored in the system
correct_username = "admin"
correct_password = "1234"

# Taking input from the user
username = input("Enter username: ")
password = input("Enter password: ")

# Checking both username and password
# Login is successful ONLY if both match
if username == correct_username and password == correct_password:
    print("Login Successful")
else:
    print("Invalid Credentials")

"""2. Pass / Fail Analyzer"""

# student marks
marks = [45, 78, 90, 33, 60]

# Counters for pass and fail students
pass_count = 0
fail_count = 0

# Loop through each student's marks
for mark in marks:

    # If marks are 50 or more → student passes
    if mark >= 50:
        pass_count += 1   # increase pass counter
    else:
        fail_count += 1   # increase fail counter

# Printing final result clearly
print("Total Students:", len(marks))
print("Number of Students Passed:", pass_count)
print("Number of Students Failed:", fail_count)

"""3. Simple Data Cleaner"""

# raw data from users
names = [" Alice ", "bob", " CHARLIE "]

# Empty list to store cleaned names
cleaned_names = []

# Loop through each name
for name in names:

    # Step 1: Remove extra spaces using strip()
    name = name.strip()

    # Step 2: Convert to lowercase
    name = name.lower()

    # Add cleaned name to new list
    cleaned_names.append(name)

# Print the final cleaned list
print("Cleaned Names:", cleaned_names)

"""4. Message Length Analyzer"""

# List of messages
messages = ["Hi", "Welcome to the platform", "OK"]

# Loop through each message
for message in messages:

    # Calculate length of the message
    length = len(message)

    # Print the message and its length
    print("Message:", message)
    print("Length:", length)

    # Check if message is longer than 10 characters
    if length > 10:
        print("Status: Long message ")
    else:
        print("Status: Short message")

    print()  # blank line for clean output

"""5. Error Message Detector"""

# List of system log entries
logs = ["INFO", "ERROR", "WARNING", "ERROR"]

# Counter for errors
error_count = 0

# Loop through each log entry
for log in logs:

    # Check if the log level is ERROR
    if log == "ERROR":
        error_count += 1   # increase error counter

# Print final result
print("Total ERROR entries:", error_count)

