# -*- coding: utf-8 -*-
"""Data Processing and Analysis Task -3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tE2-BHppOf3jaMYM5rkSRd7rwEupDLu1

```
Problem Statement 1: Employee Performance Bonus Eligibility
```
"""

employees = {
    "Ravi": 92,
    "Anita": 88,
    "Kiran": 92,
    "Suresh": 85
}

# Step 1: Find highest score
highest_score = max(employees.values())

# Step 2: Find employees with highest score
top_performers = []

for name, score in employees.items():
    if score == highest_score:
        top_performers.append(name)

# Step 3: Display result
print("Top Performers Eligible for Bonus:",
      ", ".join(top_performers),
      f"(Score: {highest_score})")

"""

```
Problem Statement 2: Search Query Keyword Analysis


"""

import string

query = "Buy mobile phone buy phone online"

# Step 1: Convert to lowercase
query = query.lower()

# Step 2: Remove punctuation
query = query.translate(str.maketrans('', '', string.punctuation))

# Step 3: Split into words
words = query.split()

# Step 4: Count frequency
frequency = {}

for word in words:
    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

# Step 5: Filter words searched more than once
result = {}

for word, count in frequency.items():
    if count > 1:
        result[word] = count

print(result)

"""

```
Problem Statement 3: Sensor Data Validation
```

"""

sensor_readings = [3, 4, 7, 8, 10, 12, 5]

valid_readings = []

for index, value in enumerate(sensor_readings):
    if value % 2 == 0:   # Check if even
        valid_readings.append((index, value))

print("Valid Sensor Readings (Hour, Value):")
print(valid_readings)

"""

```
Problem Statement 4: Email Domain Usage Analysis
```

"""

emails = [
    "ravi@gmail.com",
    "anita@yahoo.com",
    "kiran@gmail.com",
    "suresh@gmail.com",
    "meena@yahoo.com"
]

domain_count = {}

# Step 1: Count domains
for email in emails:
    domain = email.split("@")[1]

    if domain in domain_count:
        domain_count[domain] += 1
    else:
        domain_count[domain] = 1

# Step 2: Calculate percentage
total_users = len(emails)

print("Email Domain Usage Percentage:")
for domain, count in domain_count.items():
    percentage = (count / total_users) * 100
    print(f"{domain}: {int(percentage)}%")

"""

```
Problem Statement 5: Sales Spike Detection
```

"""

sales = [1200, 1500, 900, 2200, 1400, 3000]

# Step 1: Calculate average
average_sales = sum(sales) / len(sales)

# Step 2: Calculate threshold (30% above average)
threshold = average_sales * 1.30

# Step 3: Detect spikes
for index, value in enumerate(sales):
    if value > threshold:
        print(f"Day {index + 1}: {value}")

"""

```
Problem Statement 6: Duplicate User ID Detection
```

"""

user_ids = ["user1", "user2", "user1", "user3", "user1", "user3"]

id_count = {}

# Step 1: Count occurrences
for user in user_ids:
    if user in id_count:
        id_count[user] += 1
    else:
        id_count[user] = 1

# Step 2: Display duplicates
for user, count in id_count.items():
    if count > 1:
        print(f"{user} → {count} times")

