# -*- coding: utf-8 -*-
"""Task 2:Logic Building Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4ts75VTQy4X8G1uytVcdKpHWJshrGa_

# Problem 1: Unique Words in a Sentence
"""

sentence = input("Enter sentence: ")

# Step 1: Split sentence into words
words = sentence.split()

# Step 2: Convert list to set to remove duplicates
unique_words = set(words)

# Step 3: Print results
print("Unique words count:", len(unique_words))
print("Unique words:", unique_words)

"""# Problem 2: Highest Salary from Employee Data"""

employees = {
    "Ravi": 75000,
    "Anita": 68000,
    "Kiran": 72000
}

# Find employee with highest salary
highest_employee = max(employees, key=employees.get)

# Print result
print("Highest Salary:", highest_employee, "-", employees[highest_employee])

"""# Problem 3: Find Maximum and Minimum Values"""

numbers = [45, 22, 89, 10, 66]

# Step 1: Initialize
maximum = numbers[0]
minimum = numbers[0]

# Step 2: Loop through list
for num in numbers:
    if num > maximum:
        maximum = num
    if num < minimum:
        minimum = num

# Step 3: Print result
print("List:", numbers)
print("Max:", maximum)
print("Min:", minimum)

"""# Problem 4: Count Products Above a Price Threshold"""

prices = [450, 1200, 899, 1500, 300]

count = 0  # Step 1: initialize counter

for price in prices:   # Step 2: loop through list
    if price > 1000:   # Step 3: check condition
        count += 1

print("Products above 1000:", count)

"""# Problem 5: Calculate Attendance Percentage"""

attendance = ["P", "P", "A", "P", "P"]

present_count = 0

# Count number of "P"
for day in attendance:
    if day == "P":
        present_count += 1

# Calculate percentage
total_days = len(attendance)
percentage = (present_count / total_days) * 100

print("Attendance Percentage:", percentage)

"""# Problem 6: Remove Duplicate Phone Numbers"""

phone_numbers = [9876543210, 9123456789, 9876543210]

# Convert list to set
unique_numbers = set(phone_numbers)

print("Unique phone numbers:", unique_numbers)

"""# Problem 7: Count Character Frequency"""

text = "python"

char_count = {}

for ch in text:
    if ch in char_count:
        char_count[ch] += 1
    else:
        char_count[ch] = 1

print(char_count)

"""# Problem 8: Convert List to Tuple"""

numbers = [10, 20, 30]

# Convert list to tuple
numbers_tuple = tuple(numbers)

print("Tuple:", numbers_tuple)

"""# Problem 9: Check if a Key Exists in a Dictionary"""

employees = {
    "Ravi": 75000,
    "Anita": 68000,
    "Kiran": 72000
}

key_to_check = "Ravi"

if key_to_check in employees:
    print("Employee exists")
else:
    print("Employee does not exist")

"""Problem 10: Calculate Average Marks"""

marks = [70, 75, 80, 65]   # Example marks

total = 0

# Step 1: Calculate sum
for mark in marks:
    total += mark

# Step 2: Calculate average
average = total / len(marks)

print("Average Marks:", average)

