# -*- coding: utf-8 -*-
"""Task 4: Feb Internship Function with Loops – 2..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RNDSWY3DAcCEE_aGAibkyEJPTbwEpdb

```
Problem 1: Mobile Recharge Validation System
```
"""

def validate_recharge(amount):
    valid_plans = [199, 299, 399, 599]

    if amount < 50:
        print(" Recharge amount must be at least ₹50")
        return False
    elif amount not in valid_plans:
        print(" Invalid plan. Available plans: 199, 299, 399, 599")
        return False
    else:
        print(" Recharge Successful!")
        return True


# Retry system using while loop
while True:
    amount = int(input("Enter recharge amount: ₹"))

    if validate_recharge(amount):
        break
    else:
        print(" Please try again.\n")

"""

```
Problem 2: Inventory Reorder Alert System
```

"""

def check_inventory(stock_data):
    for product, quantity in stock_data.items():
        if quantity < 15:
            print(f" {product}: Reorder Alert (Stock = {quantity})")
        else:
            print(f" {product}: Stock OK (Stock = {quantity})")


# Sample inventory dictionary
inventory = {
    "Rice": 20,
    "Wheat": 10,
    "Sugar": 5,
    "Oil": 18,
    "Salt": 12
}

check_inventory(inventory)

"""

```
Problem 3: Student Result Processing System
```

"""

def process_result(marks):
    total = 0

    # Loop to calculate total
    for mark in marks:
        total += mark

    average = total / len(marks)

    # Check Pass/Fail
    if average >= 50:
        return average, "Pass"
    else:
        return average, "Fail"


# Example usage
student_marks = [60, 45, 70, 50, 40]

avg, result = process_result(student_marks)

print("Average Marks:", avg)
print("Result:", result)

"""

```
Problem 4: Cab Fare Estimator with Retry Option
```

"""

def calculate_fare(distance, peak):
    base_fare = 50
    per_km_rate = 12

    fare = base_fare + (distance * per_km_rate)

    if peak.lower() == "yes":
        fare += fare * 0.25   # 25% extra during peak hour

    return fare


# Retry system using while loop
while True:
    try:
        distance = float(input("Enter distance in km: "))
        peak = input("Is it peak hour? (yes/no): ")

        total_fare = calculate_fare(distance, peak)

        print(f" Total Fare: ₹{total_fare:.2f}")

        retry = input("Do you want to calculate again? (yes/no): ")
        if retry.lower() != "yes":
            print("Thank you for using Cab Fare Estimator!")
            break

    except ValueError:
        print(" Please enter valid numeric distance.\n")

"""

```
Problem 5: Employee Attendance Eligibility Checker
```

"""

def check_attendance(attendance_list):
    present_days = 0

    # Loop to count present days
    for day in attendance_list:
        if day == "P":
            present_days += 1

    total_days = len(attendance_list)
    percentage = (present_days / total_days) * 100

    # Check eligibility
    if percentage >= 75:
        return percentage, "Eligible"
    else:
        return percentage, "Not Eligible"


# Example usage
attendance = ["P", "P", "A", "P", "P", "A", "P", "P"]

percent, status = check_attendance(attendance)

print(f"Attendance Percentage: {percent:.2f}%")
print("Status:", status)

"""

```
Problem 6: Password Strength Checker
```

"""

def check_password(password):
    has_digit = False
    has_special = False

    # Minimum length check
    if len(password) < 8:
        return "Weak Password (Minimum 8 characters required)"

    # Loop over string
    for char in password:
        if char.isdigit():
            has_digit = True
        if char in "@#$":
            has_special = True

    # Conditions
    if has_digit and has_special:
        return "Strong Password "
    else:
        return "Weak Password (Must include at least one digit and one special character @#$)"


# Example usage
pwd = input("Enter your password: ")
result = check_password(pwd)
print(result)

