# -*- coding: utf-8 -*-
"""Task 7: Feb Internship Logic Building Task – 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EcoCRmRBPrro7IxzP02k9MaYYW2h4U6F

```
Problem 1: Smart Light Controller
```
"""

class SmartLight:
    def __init__(self, name):
        self.name = name
        self.status = "OFF"

    def turn_on(self):
        self.status = "ON"

    def turn_off(self):
        self.status = "OFF"

    def display_status(self):
        print(self.name, "is", self.status)


# Input
light_name = input("Light Name: ")
action = input("Action (ON/OFF): ")

# Object creation
light = SmartLight(light_name)

# Perform action
if action.upper() == "ON":
    light.turn_on()
elif action.upper() == "OFF":
    light.turn_off()

# Display result
light.display_status()

"""

```
Problem 2: Employee ID Card System
```

"""

class Employee:
    def __init__(self, name, emp_id, department):
        self.name = name
        self.emp_id = emp_id
        self.department = department

    def display_id_card(self):
        print("Employee ID Card")
        print("Name:", self.name)
        print("ID:", self.emp_id)
        print("Department:", self.department)
# Input
name = input("Employee Name: ")
emp_id = input("Employee ID: ")
department = input("Department: ")

# Object creation
emp = Employee(name, emp_id, department)

# Display ID Card
emp.display_id_card()

"""

```
Problem 3: Mobile Contact Record
```

"""

class Contact:
    def __init__(self, name, phone):
        self.name = name
        self.phone = phone

    def display_contact(self):
        print("Contact Saved")
        print("Name:", self.name)
        print("Phone:", self.phone)


# Input
name = input("Contact Name: ")
phone = input("Phone Number: ")

# Object creation
contact = Contact(name, phone)

# Display contact information
contact.display_contact()

"""

```
Problem 4: Product Price Tag Generator
```

"""

class Product:
    def __init__(self, name, price):
        self.name = name
        self.price = price

    def display_price_tag(self):
        print("Product:", self.name)
        print("Price: ₹" + str(self.price))


# Input
name = input("Product Name: ")
price = input("Price: ")

# Object creation
product = Product(name, price)

# Display price tag
product.display_price_tag()

"""

```
Problem 5: Movie Rating Display System
```

"""

class Movie:
    def __init__(self, name, rating):
        self.name = name
        self.rating = rating

    def display_movie(self):
        print("Movie:", self.name)
        print("Rating:", self.rating, "/ 5")


# Input
name = input("Movie Name: ")
rating = input("Rating: ")

# Object creation
movie = Movie(name, rating)

# Display movie details
movie.display_movie()

"""

```
Problem 6: Delivery Address Manager
```

"""

class Delivery:
    def __init__(self, name, address):
        self.name = name
        self.address = address

    def display_details(self):
        print("Delivery Details")
        print("Customer:", self.name)
        print("Address:", self.address)


# Input
name = input("Customer Name: ")
address = input("Address: ")

# Object creation
delivery = Delivery(name, address)

# Display delivery details
delivery.display_details()

