# -*- coding: utf-8 -*-
"""NLP – 5 (Token Classification: POS Tagging & Chunking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6fDQvXrBDE0_OSPpgNvGO6hZ-WUJShu
"""

!pip install evaluate seqeval datasets
from datasets import load_dataset
from transformers import AutoTokenizer, DataCollatorForTokenClassification
from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer
import numpy as np
import evaluate

# 1. LOAD DATASET
data_files = {
    "train": "https://huggingface.co/datasets/conll2003/resolve/refs%2Fconvert%2Fparquet/conll2003/train/0000.parquet",
    "validation": "https://huggingface.co/datasets/conll2003/resolve/refs%2Fconvert%2Fparquet/conll2003/validation/0000.parquet",
    "test": "https://huggingface.co/datasets/conll2003/resolve/refs%2Fconvert%2Fparquet/conll2003/test/0000.parquet"
}
dataset = load_dataset("parquet", data_files=data_files)

# 2. DYNAMIC LABEL LIST SETUP
# Extract unique labels from the training set to avoid index out of bounds
unique_labels = set()
for item in dataset["train"]["pos_tags"]:
    unique_labels.update(item)
label_list = [str(i) for i in range(max(unique_labels) + 1)]

# 3. TOKENIZATION & ALIGNMENT
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)
    labels = []
    for i, label in enumerate(examples["pos_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        labels.append(label_ids)
    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenized_ds = dataset.map(tokenize_and_align_labels, batched=True)

# 4. MODEL SETUP
model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label_list),
    id2label={i: l for i, l in enumerate(label_list)},
    label2id={l: i for i, l in enumerate(label_list)}
)

# 5. EVALUATION METRIC
seqeval = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)
    true_predictions = [[label_list[p] for (p, l) in zip(prediction, label) if l != -100] for prediction, label in zip(predictions, labels)]
    true_labels = [[label_list[l] for (p, l) in zip(prediction, label) if l != -100] for prediction, label in zip(predictions, labels)]
    results = seqeval.compute(predictions=true_predictions, references=true_labels)
    return {"precision": results["overall_precision"], "recall": results["overall_recall"], "f1": results["overall_f1"], "accuracy": results["overall_accuracy"]}

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("Running initial evaluation...")
eval_results = trainer.evaluate()
print(f"Evaluation Results: {eval_results}")

from transformers import pipeline

# Initialize the pipeline for token classification
ner_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="none"
)

# Grab an example from the validation set
sample_index = 0
sample_text = " ".join(dataset["validation"][sample_index]["tokens"])

# Run prediction
predictions = ner_pipeline(sample_text)

print(f"Sentence: {sample_text}")
print("\nPredictions:")
for pred in predictions:
    print(f"Token: {pred['word']:10} | Tag ID: {pred['entity']:2} | Score: {pred['score']:.4f}")